# syntax = docker/dockerfile:latest

FROM alpine AS base

FROM golang:1.16.4 AS go-builder
WORKDIR /go/app
COPY go.mod .
COPY go.sum .

RUN --mount=type=cache,target=/root/.cache/go go mod download

COPY . /go/app

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/app/main /go/app/cmd/node/main.go

FROM base
RUN apk add --no-cache iptables
COPY --from=go-builder /go/app/main /forta-node
EXPOSE 8089 8090
