{
 "title": "Forta Node",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "JSON-RPC",
   "type": "timeseries",
   "description": "Scan and trace API activity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "forta_json_rpc_activity_seconds"
    }
   ]
  },
  {
   "title": "Analyzer",
   "type": "timeseries",
   "description": "Input/output times observed at the analyzer layer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "forta_analyzer_activity_seconds"
    }
   ]
  },
  {
   "title": "Stream",
   "type": "timeseries",
   "description": "Input stream activity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "forta_stream_activity_seconds" }
   ]
  },
  {
   "title": "Publisher",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "forta_publisher_activity_seconds"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Presence of errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "forta_bot_registry_errors" },
    { "expr": "forta_json_rpc_errors" },
    { "expr": "forta_publisher_errors" },
    { "expr": "forta_telemetry_errors" }
   ]
  },
  {
   "title": "Inspector",
   "type": "timeseries",
   "description": "Inspection results",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "forta_inspector" }
   ]
  },
  {
   "title": "Active Bots",
   "type": "timeseries",
   "description": "Active bot counts (started and running)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "forta_active_bots" }
   ]
  },
  {
   "title": "Bot Registry",
   "type": "timeseries",
   "description": "Bot assignment list detection activity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "forta_bot_registry_activity_seconds"
    }
   ]
  },
  {
   "title": "Telemetry and logs",
   "type": "timeseries",
   "description": "Telemetry and bot logs activity",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "forta_telemetry_activity_seconds"
    }
   ]
  }
 ]
}