// Code generated by MockGen. DO NOT EDIT.
// Source: clients/agentgrpc/dialer.go

// Package mock_agentgrpc is a generated GoMock package.
package mock_agentgrpc

import (
	reflect "reflect"

	agentgrpc "github.com/forta-network/forta-node/clients/agentgrpc"
	config "github.com/forta-network/forta-node/config"
	gomock "github.com/golang/mock/gomock"
)

// MockBotDialer is a mock of BotDialer interface.
type MockBotDialer struct {
	ctrl     *gomock.Controller
	recorder *MockBotDialerMockRecorder
}

// MockBotDialerMockRecorder is the mock recorder for MockBotDialer.
type MockBotDialerMockRecorder struct {
	mock *MockBotDialer
}

// NewMockBotDialer creates a new mock instance.
func NewMockBotDialer(ctrl *gomock.Controller) *MockBotDialer {
	mock := &MockBotDialer{ctrl: ctrl}
	mock.recorder = &MockBotDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotDialer) EXPECT() *MockBotDialerMockRecorder {
	return m.recorder
}

// DialBot mocks base method.
func (m *MockBotDialer) DialBot(ac config.AgentConfig) (agentgrpc.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DialBot", ac)
	ret0, _ := ret[0].(agentgrpc.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DialBot indicates an expected call of DialBot.
func (mr *MockBotDialerMockRecorder) DialBot(ac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialBot", reflect.TypeOf((*MockBotDialer)(nil).DialBot), ac)
}
