name: Go
description: Validate and test Go code
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: 1.16
  - uses: actions/cache@v2
    with:
      path: |
        ~/go/pkg/mod
        ~/.cache/go-build
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-
  - name: Build
    shell: bash
    run: go build -v ./...
  - name: Run unit tests
    shell: bash
    run: make test
